### ISSUE TITLE
VFX Editing

### ISSUE THREAD

**Issue by SyDant** [Halyul/aklive2d#11]
Hey, thanks in advance! By the way, I'm currently looking for animated versions of each character to use in creating Android/iPhone wallpapers.

Right now, I'm trying to figure out how to export the animations with a transparent background (alpha channel) so I can later add VFX effects and a animating background. Is there a solution like exporting as .mov, .gif, or .mp4?? Or quick way to record them one by one in the web version, even though the resolution might be lower :(

i Try research a bit.. since this animation using spine2d .atlas and .skel, Also, in Spine2D, you can export as a video with a transparent background, but I can't afford to buy the software since I only need it for exporting.

**Comment by Halyul** [comment]
You may want to check [this](https://stackoverflow.com/questions/19235286/convert-html5-canvas-sequence-to-a-video-file) out. Canvas allows you to capture videos from it, but the background may still be an issue, i.e. no transparency.

**Comment by SyDant** [comment]
Thanks for Reply, i will research again about canvas capture
