### ISSUE TITLE
Default settings

### ISSUE THREAD

**Issue by inspiredscout** [Halyul/aklive2d#16]
Hello. i cant find how to change default setting for building operator webpages, like default logo or framerate. Maybe some file like default_setting.yaml?

**Comment by Halyul** [comment]
- Default logo can be changed in operator config yaml and put the corresponding file into `<config.folder.operator_data>/<config.folder.share>/logo` folder
- Default framerate is hard written at [spine-player.js L7595](https://github.com/Halyul/aklive2d/blob/97a1d008c9085fb70cf59ea9cc38661f78248c41/showcase/src/libs/spine-player.js#L7595) and [spine-player.js L11037](https://github.com/Halyul/aklive2d/blob/97a1d008c9085fb70cf59ea9cc38661f78248c41/showcase/src/libs/spine-player.js#L11037)
